### ISSUE TITLE
Path problems remain

### ISSUE THREAD

**Issue by elear** [iot-onboarding/mud-visualizer#17]
Maybe I'm breaking something, but when I try to load the visualizer as a submodule for mudmaker, I end up with img directory problems, particularly in renderer.js.  That's because it's being included at a directory above where it might ordinarily run.  Thoughts?

**Comment by Vafa-Andalibi** [comment]
Did you run `create_symlinks.sh` after cloning the submodule? Even with that you are having problem with images?

**Comment by elear** [comment]
Ok, they remain less than I thought!
