### ISSUE TITLE
Dumb question about this_node_obj.is_controlle_or_mycontroller

### ISSUE THREAD

**Issue by elear** [iot-onboarding/mud-visualizer#9]
Where is that value even set in renderer.js

**Comment by Vafa-Andalibi** [comment]
That's a method in the node class defined in [scripts/helpers.js](https://github.com/iot-onboarding/mud-visualizer/blob/master/scripts/helpers.js) that just checks whether the node is controller or mycontroller. We have two methods that mark a node as controller, i.e. [mark_as_my_controller() ](https://github.com/iot-onboarding/mud-visualizer/blob/8fd46b04dd06cd50078a585f9f275b3409028b5f/scripts/helpers.js#L228) and [mark_as_controller() ](https://github.com/iot-onboarding/mud-visualizer/blob/8fd46b04dd06cd50078a585f9f275b3409028b5f/scripts/helpers.js#L235).
 
In the [mud.js line 777](https://github.com/iot-onboarding/mud-visualizer/blob/8fd46b04dd06cd50078a585f9f275b3409028b5f/scripts/mud.js#L777) for instance sets the node as controller. [Line 298](https://github.com/iot-onboarding/mud-visualizer/blob/8fd46b04dd06cd50078a585f9f275b3409028b5f/scripts/mud.js#L298) sets it as my-controller.

**Comment by elear** [comment]
Got it!
